---
name: npm-publish
run-name: ${{ github.actor }} is pushing to npm
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm test
      - run: npm stage publish
